// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/get-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
var services = [
  {
    title: "Website Design & Creation",
    description: "Start-to-finish custom website design. Market and brand research, a few design directions, then built out as a real working site with a hands-on pass before launch.",
    features: [
      "Custom design, not a template",
      "SEO and meta set up properly",
      "Works on phones, tablets, and desktop",
      "CMS so you can edit without us"
    ]
  },
  {
    title: "Redesign & SEO Optimisation",
    description: "Audit and fix slow, dated, or under-performing sites. Speed, layout, and accessibility improvements aimed at the things that cost traffic and conversions.",
    features: [
      "Core Web Vitals and page speed",
      "UX clean-up where it matters",
      "WCAG accessibility pass",
      "Analytics and event tracking"
    ]
  },
  {
    title: "E-commerce, Portals & Web Apps",
    description: "Client portals, booking systems, retail storefronts, and internal dashboards. Built as full apps, not glued-together plugins, with full ownership handed over.",
    features: [
      "Full apps, not glued-together plugins",
      "Logins, roles, and user areas",
      "Stripe, calendars, CRM integrations",
      "Cloud hosting set up for you"
    ]
  }
];
var get_services_default = defineTool({
  name: "get_services",
  title: "Get services",
  description: "List the web design, SEO, and web application services offered by AI Web Solution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
var tiers = [
  {
    name: "Basic",
    startingPriceGBP: 300,
    description: "A single page, built to convert. Good for freelancers, product launches, or a small business that does not need a full site yet.",
    features: [
      "Custom design, hand-reviewed",
      "Works on phones and laptops",
      "SEO and meta tags set up",
      "Contact form that actually sends",
      "Pre-launch QA pass",
      "14 days of support after go-live"
    ]
  },
  {
    name: "Pro",
    startingPriceGBP: 500,
    description: "A full website for businesses that need more than one page. Structure, a CMS, and the basics that let you keep editing without us.",
    features: [
      "Everything in Basic",
      "Up to 5 pages",
      "Full SEO and analytics setup",
      "CMS so you can edit copy",
      "Page speed and Core Web Vitals",
      "Blog or news section",
      "30 days of priority support"
    ]
  },
  {
    name: "Expert",
    startingPriceGBP: 1e3,
    description: "Bigger builds with real depth: 3D scenes, client portals, or a proper e-commerce store. Made to handle traffic and grow as you do.",
    popular: true,
    features: [
      "Everything in Pro",
      "3D scenes or full portal app",
      "E-commerce store and checkout",
      "Custom logic, workflows, roles",
      "Database and user management",
      "Stripe, CRM, and other APIs",
      "Cloud hosting and deployment",
      "90 days of dedicated support"
    ]
  },
  {
    name: "Full Brand",
    startingPriceGBP: 2e3,
    description: "Brand identity built at the same time as the platform. Logo, type, palette, voice, and how all of it shows up across every page of the Expert build.",
    features: [
      "Everything in Expert",
      "Logo system and identity",
      "Type, colour, and motion rules",
      "Brand voice and messaging guide",
      "Social and marketing asset kit",
      "6 months of ongoing support"
    ]
  }
];
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get pricing tiers",
  description: "List AI Web Solution's pricing tiers with starting prices in GBP. Prices are starting points; final quotes depend on scope.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(tiers, null, 2) }],
    structuredContent: { tiers, currency: "GBP" }
  })
});

// src/lib/mcp/tools/get-process.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
var steps = [
  { step: 1, name: "Discovery", description: "Understand your business, goals, and audience." },
  { step: 2, name: "Design", description: "Draft directions and refine the visual system with you." },
  { step: 3, name: "Build", description: "Implement the site with clean code, SEO, and accessibility." },
  { step: 4, name: "Launch & Support", description: "Ship the site and support you after go-live." }
];
var get_process_default = defineTool3({
  name: "get_process",
  title: "Get delivery process",
  description: "Return the 4-step delivery process AI Web Solution uses for every project.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(steps, null, 2) }],
    structuredContent: { steps }
  })
});

// src/lib/mcp/tools/submit-contact-enquiry.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
var submit_contact_enquiry_default = defineTool4({
  name: "submit_contact_enquiry",
  title: "Submit contact enquiry",
  description: "Send a project enquiry to AI Web Solution. The team responds within 24 hours with a quote and starting plan.",
  inputSchema: {
    name: z.string().trim().min(1).max(100).describe("Full name of the person enquiring."),
    email: z.string().trim().email().max(255).describe("Reply-to email address."),
    industry: z.string().trim().max(100).optional().describe("Industry or type of business."),
    budget: z.enum(["300plus", "500plus", "1000plus", "2000plus"]).optional().describe("Budget tier: 300plus (\xA3300+ Basic), 500plus (\xA3500+ Pro), 1000plus (\xA31,000+ Expert), 2000plus (\xA32,000+ Full Brand)."),
    message: z.string().trim().max(1e3).optional().describe("What you are building, timelines, and anything else that helps us quote.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => {
    const env = globalThis.Deno?.env;
    const supabaseUrl = env?.get("SUPABASE_URL");
    const anonKey = env?.get("SUPABASE_ANON_KEY") ?? env?.get("SUPABASE_PUBLISHABLE_KEY");
    if (!supabaseUrl || !anonKey) {
      return {
        content: [{ type: "text", text: "Contact form is not available right now." }],
        isError: true
      };
    }
    try {
      const res = await fetch(`${supabaseUrl}/functions/v1/send-contact-email`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${anonKey}`,
          apikey: anonKey
        },
        body: JSON.stringify(input)
      });
      if (!res.ok) {
        const text = await res.text();
        return {
          content: [{ type: "text", text: `Failed to submit enquiry: ${res.status} ${text}` }],
          isError: true
        };
      }
      return {
        content: [
          {
            type: "text",
            text: `Enquiry submitted for ${input.name} <${input.email}>. The team will respond within 24 hours.`
          }
        ],
        structuredContent: { ok: true }
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Failed to submit enquiry: ${err.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ai-web-solution-mcp",
  title: "AI Web Solution",
  version: "0.1.0",
  instructions: "Public MCP server for AI Web Solution (aiwebsolution.co.uk). Use `get_services`, `get_pricing`, and `get_process` to describe what the studio offers, and `submit_contact_enquiry` to send a project enquiry that the team will respond to within 24 hours.",
  tools: [get_services_default, get_pricing_default, get_process_default, submit_contact_enquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
